file=open("file.txt","w")
file.write("Hello,this is the first line\n")
file.close()
file=open("file.txt","a")
file.write("This line is added using append mode\n")
file.close()
file=open("file.txt","r")
content=file.read()
print(content)
file.close()
